### ISSUE TITLE
U6 - Export Anonymous Data Is Optional

### ISSUE THREAD

**Issue by AustinH5544** [Sanmeet-EWU/cscd-488-490-project-hrv-monitoring#4] opened 2024-10-21 22:28 UTC
**As a** person who values my privacy
**I need** to ensure that no data is taken off my device, anonymous or not
**So that** I do not have to worry about my data getting leaked
### Details and Assumptions
* Toggle for data being sent
### Acceptance Criteria
```gherkin
Given that I DO NOT want my data sent
When I go into my setting and toggle the transmit data toggle OFF
Then the app will no longer transmits my data.
```
```gherkin
Given that I DO want my data sent
When I go into settings and turn the transmit toggle ON
Then the app will start transmitting the data.
```

**Comment by BDullanty** [comment] 2024-10-23 20:28
Duplicate of U7

**Closed as not planned by BDullanty** 2024-10-23 20:28 UTC
Labels: enhancement
